# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add_numbers <- function(a, b) {
    .Call('_demoRcppPkg_add_numbers', PACKAGE = 'demoRcppPkg', a, b)
}

read_sbml <- function(file_path) {
    .Call('_demoRcppPkg_read_sbml', PACKAGE = 'demoRcppPkg', file_path)
}

